### ISSUE TITLE
move env to binder branch

### ISSUE THREAD

**Issue by rsignell-usgs** [friedrichknuth/covid_dashboard#1]
If the environment is moved to a binder branch, you can run on binder, but then modify notebooks without rebuilding the image, as described [here](https://discourse.jupyter.org/t/tip-embed-custom-github-content-in-a-binder-link-with-nbgitpuller/922).   I'll submit a PR shortly.

**Comment by rsignell-usgs** [comment]
Hmm, actually, I guess I can't submit a PR to a binder branch if there is no binder branch yet?

**Comment by tjcrone** [comment]
Thanks for this update @rsignell-usgs. This is very helpful!

**Comment by rsignell-usgs** [comment]
Just a note that if we introduce code or notebooks that require additional libraries, we should add them to the `environment.yaml` files in both the `master` and `binder` branches.  

The `environment.yaml` file in the `master` branch is for folks who want to recreate the environment locally.

The `environment.yaml` file in the `binder` branch is for running on binder.   As long at that environment doesn't change and binder doesn't rebuild the docker image!  

Binder pulls the code and notebook from master using git after it loads the environment, so we can modify those all we want and use the same image on binder.

**Comment by benholtzman** [comment]
y'all seen this?:
https://covidtracking.com/data/

**Comment by tjcrone** [comment]
This is cool @benholtzman! This issue is closed though, and related to something else. Can I ask you to start another issue regarding data sources? This is something that we definitely need to discuss. We started a discussion at #5, but it really needs its own issue. Thanks!
